config/routes.rb
Rails.application.routes.draw do
  
  devise_for :jefe_areas
  devise_for :directors
  devise_for :users
  get 'sessions/new'

      resources :pqrs
   

   get "persona/create"
   get "pqr/create"
   get "welcome/index"
   get "welcome/login"
   get "welcome/tramites"
   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
  
   #get"empleados/index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  #root 'welcome#tramitar'
 # root 'empleados#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/jefe_area.rb
class JefeArea < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pqr.rb
class Pqr < ApplicationRecord
    mount_uploader :archivo, ArchivoUploader

end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
 

  def hello
    render html: "hello, world!"
  end
end

app/controllers/pqrs_controller.rb
class PqrsController < ApplicationController
  before_action :set_pqr, only: [:show, :edit, :update, :destroy]

  # GET /pqrs
  # GET /pqrs.json
  def index
    @pqrs = Pqr.all


  end

  # GET /pqrs/1
  # GET /pqrs/1.json
  # pqrs_controller.rb
  def show
  
  
  
  end

  # GET /pqrs/new
  def new
    @pqr = Pqr.new
  end

  # GET /pqrs/1/edit
  def edit
  end

  # POST /pqrs
  # POST /pqrs.json
  def create
    @pqr = Pqr.new(pqr_params)

    respond_to do |format|
      if @pqr.save
        format.html { redirect_to @pqr, notice: 'Pqr fue enviado con exito.' }
        format.json { render :show, status: :created, location: @pqr }
      else
        format.html { render :new }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pqrs/1
  # PATCH/PUT /pqrs/1.json
  def update
    respond_to do |format|
      if @pqr.update(pqr_params)
        format.html { redirect_to @pqr, notice: 'Pqr was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr }
      else
        format.html { render :edit }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqrs/1
  # DELETE /pqrs/1.json
  def destroy
    @pqr.destroy
    respond_to do |format|
      format.html { redirect_to pqrs_url, notice: 'Pqr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr
      @pqr = Pqr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_params
      params.require(:pqr).permit(:nombre, :apellido, :correo, :cdeula, :telefono, :tipo, :archivo, :descripcion, :tiempo_sol, :tiempo_res)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
  
  end
  
  def login
  
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pqrs_helper.rb
module PqrsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
    

<head>
 <%= favicon_link_tag 'logo.png' %>
 </head>
 
 <%= yield %>
 
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
 

app/views/pqrs/_form.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
	<title>Formulario de registro</title>
	<link rel="stylesheet"  href="css/registro.css">
	<link rel="stylesheet" href="css/index_GENERAL.css"> 
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
</head>
<body>


<div class="form-register">
<h2 class="form__titulo">Tramitar PQRS</h2>

<div class="contenedor-inputs">
<%= form_with(model: pqr, local: true) do |form| %>
  <% if pqr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pqr.errors.count, "error") %> prohibited this pqr from being saved:</h2>

      <ul>
      <% pqr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
     
    	
     <%= form.text_field :nombre, id: :pqr_nombre, :class=>"input-48", :placeholder=>"Nombre", required: 'true'%>
	
	 <%= form.text_field :apellido, id: :pqr_apellido, :class => "input-48", :placeholder=>"Apellidos" , required: 'true'%>
	 
	  <%= form.email_field :correo, id: :pqr_correo, :class => "input-100", :placeholder=>"Correo", required: 'true'%>
	 
	 <%=form.text_field :cdeula, id: :pqr_cdeula,:class => "input-48", :placeholder=>"Cedula", required: 'true' %>
	
    <%=form.text_field :telefono, id: :pqr_telefono,:class => "input-48", :placeholder=>"Teléfono", required: 'true'%>
	 

    <%= form.select "alert", options_for_select([['Peticiones', 0], ['Quejas', 1],['Reclamos', 2],['Sujerencia', 3]]), :id => "pqr_tipo " , :class => 'input-48' %>
    <%= form.file_field :archivo, id: :pqr_archivo,  :class => "input-48"%>
    
    
    <%= form.text_area :descripcion, id: :pqr_descripcion, :class => "input-100", :cols=>"70", :rows=>"12", :placeholder=>"Escriba su solicitud", required: 'true' %>
	 	<hr width="100%">
	 
	 
	<center> 
	
	<%= link_to "Back", root_path , :class => "btn-enviar", :id => "" %>
	
	<%= form.submit :class => "btn-enviar", :value => "Enviar" %>
	
	
	
	</center>
    
	     <% end %>
</div>
</div>


</body>
</html>

app/views/pqrs/edit.html.erb
<h1>Editing Pqr</h1>

<%= render 'form', pqr: @pqr %>

<%= link_to 'Show', @pqr %> |
<%= link_to 'Back', pqrs_path %>

app/views/pqrs/index.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE HTML>
<html lang="es">
    <head>
       <title>Director</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	 <link rel="stylesheet" href="css/index_GENERAL.css"> 
	 <link rel="stylesheet"  href="css/registro.css">
	 <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	 <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    </head>
    
    <body>
       <div class="contenedor">
          <header>
           <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Director</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%=root_path%>">Inicio<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="inicio_sesi%C3%B3n.html">Crear usuario</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="registro_comprador.html"></a>
            </li>
          </ul>
          
         
        </div>
      </nav>
         
          </header>
          <div class="contenedor_1">
             <div id="contenido">
      
        <div id="page-wrapper">
            
            <div class="container-fluid"> 
                         
                <div class="text-center color2 jumbotron">
                    <h2 id="titulo" class="admi" > PQRS</h2>
                  
                </div>
              
                
                <div>
                         
                         
                         
                         
            
                         
                         
                         
                         
                         
                         
                         
                         <div class="row">
                           <div class="col-md-12 table-responsive">
                              
                                <table class="table table-sm">
                                  <thead>
                                  
                                    <tr class="bg-info money">
                                      <th><center>Nombre</center></th>
                                      <th><center>Apellido</center></th>
                                      <th><center>Cedula</center></th>
                                      <th><center>Correo</center></th>
                                  
                                      <th><center>Tipo</center></th>
                                     
                                      <th><center>Archivo</center></th>
                                      <th><center>Fecha</center></th>
                                      <th><center>Estado</center></th>
                                      
                                     <th><center>Opción</center></th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                   <% @pqrs.each do |pqr| %>
                                                  
                                                <tr>
                                                 <td><%= pqr.nombre %></td>
                                                  <td><%= pqr.apellido %></td>
                                                  <td><%= pqr.cdeula %></td>
                                                  <td><%= pqr.correo %></td>
                        
                                                   <td><%= pqr.tipo %></td>
                                                  
                                                   <td> <%= link_to "ver Archivo", pqr.archivo_url%></td>
                                                   
                                                  <td><%=pqr.tiempo_sol%></td>
                                                  <td><%= pqr.active %></td>
                                                  <td>
                                                        
                                                     <center>
                                                    <%= link_to 'PDF', pqr,  :class => "btn btn-danger btn-md" %> 
                                                  </center>
                                                  </td>
                                                </tr>
                                                 
                                <% end %>
                                  </tbody>
                                </table>
                           </div>
                         </div>  
                         
                           
                </div>
                
                
                
                
                
                
                
                
                
                
                
                
                
            </div>
          

        </div>
    

    </div>
   

         
          
           </div>
       </div>
       
      
    </body>
    
</html>

app/views/pqrs/new.html.erb
<%= render 'form', pqr: @pqr %>

<%= link_to 'Back', pqrs_path %>

app/views/pqrs/show.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    
	<title>PQR-PDF</title> 
</head>
<body>

<div class="conte"> 
  <center>
      <div class="hoja">

          <p><h4>Santa marta, Magdalena</h4>
             <h6><%= @pqr.tiempo_sol %></h6>
          
          </p>
          
          <div class="datos">
            <h5>
               <p>Empresa ABC</p>
                <p>Director General</p>
                <p>PRESENTE</p>
               </h5>
               
            <p>Estimado Sr. Director</p>
            
            
              
          </div>
          
          <div class="coment">
             
             <p>
                  <%= @pqr.descripcion %>
             </p>
             
             
              
          </div>
          
          <div class="datos_2">
             
             <p><%= @pqr.nombre %> <%= @pqr.apellido %></p>
             <p><%= @pqr.cdeula %></p>
             <p><%= @pqr.telefono %></p>
             <p><%= @pqr.correo %></p>
              
              
          </div>


      </div>
      
</center>

</div>
<center><%= link_to "Back",root_path , :class => "btn-enviar", :id => "" %></center>

<style>
    *{
    font-family: sans-serif;
}

.btn-enviar{

	background: crimson;
	color: #fff;
	margin:auto;
	padding: 10px 40px;
	cursor:pointer;
}

.btn-enviar:active{
	transform: scale(1.05);
}

.conte{
    width: 100%;
    height: auto;
    background: #ddd;
    text-align: center;
    padding-top: 30px;
    padding-bottom: 20px;
}

.hoja{
    width: 50%;
    height: 700px;
    background: #fff;
    padding-top: 90px;
    text-align: center;
    padding-left: 50px;
    padding-right: 50px;
    border: solid 1px;
}
.hoja p {
   
}

.datos{
    margin-top: 60px; 
}
.datos p{
    text-align: left;
    font-size: 12px;
    margin: 5px;
}

.coment{
    margin-top: 40px;
    height: auto;
    text-align: left;
    overflow-wrap: break-word;
}

.coment p{
    margin: 0;
    font-size: 11px;
}
.datos_2{
    margin-top: 60px; 
}
.datos_2 p{
    text-align: left;
    font-size: 12px;
    margin: 5px;
}

</style>

</body>

</html>

app/views/pqrs/show.pdf.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    
	<title>PQR-PDF</title> 
</head>
<body>

<div class="conte"> 
  <center>
      <div class="hoja">

          <p><h4>Santa marta, Magdalena</h4>
             <h6><%= @pqr.tiempo_sol %></h6>
          
          </p>
          
          <div class="datos">
            <h5>
               <p>Empresa ABC</p>
                <p>Director General</p>
                <p>PRESENTE</p>
               </h5>
               
            <p>Estimado Sr. Director</p>
            
            
              
          </div>
          
          <div class="coment">
             
             <p>
                  <%= @pqr.descripcion %>
             </p>
             
             
              
          </div>
          
          <div class="datos_2">
             
             <p><%= @pqr.nombre %> <%= @pqr.apellido %></p>
             <p><%= @pqr.cdeula %></p>
             <p><%= @pqr.telefono %></p>
             <p><%= @pqr.correo %></p>
              
              
          </div>


      </div>
      
</center>

</div>
<center><%= link_to "Back",root_path , :class => "btn-enviar", :id => "" %></center>

<style>
    *{
    font-family: sans-serif;
}

.btn-enviar{

	background: crimson;
	color: #fff;
	margin:auto;
	padding: 10px 40px;
	cursor:pointer;
}

.btn-enviar:active{
	transform: scale(1.05);
}

.conte{
    width: 100%;
    height: auto;
    background: #ddd;
    text-align: center;
    padding-top: 30px;
    padding-bottom: 20px;
}

.hoja{
    width: 50%;
    height: 700px;
    background: #fff;
    padding-top: 90px;
    text-align: center;
    padding-left: 50px;
    padding-right: 50px;
    border: solid 1px;
}
.hoja p {
   
}

.datos{
    margin-top: 60px; 
}
.datos p{
    text-align: left;
    font-size: 12px;
    margin: 5px;
}

.coment{
    margin-top: 40px;
    height: auto;
    text-align: left;
    overflow-wrap: break-word;
}

.coment p{
    margin: 0;
    font-size: 11px;
}
.datos_2{
    margin-top: 60px; 
}
.datos_2 p{
    text-align: left;
    font-size: 12px;
    margin: 5px;
}

</style>

</body>

</html>

app/views/welcome/administrativa.html.erb
<!DOCTYPE HTML>
<html lang="es">
    <head>
       <title>administrativa</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	 <link rel="stylesheet" href="css/index_GENERAL.css"> 
	 <link rel="stylesheet"  href="css/registro.css">
	 <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	 <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script>
	<script src="js/jquery.nivo.slider.js"></script>
  
   
  
    </head>
    
    <body>
       <div class="contenedor">
          <header>
           <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Administrativa</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Inicio<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="inicio_sesi%C3%B3n.html">Crear usuario</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="registro_comprador.html"></a>
            </li>
          </ul>
          
        </div>
      </nav>
         
          </header>
           <div class="contenedor_1">
             <div id="contenido">
      
        <div id="page-wrapper">
            
            <div class="container-fluid"> 
                         
                <div class="text-center color2 jumbotron">
                    <h2 id="titulo" class="admi" > PQRS</h2>
                  
                </div>
              
                
                <div>
                         
                         
                         
                         
            
                         
                         
                         
                         
                         
                         
                         
                         <div class="row">
                           <div class="col-md-12 table-responsive">
                              
                                <table class="table table-sm">
                                  <thead>
                                  
                                    <tr class="bg-info money">
                                      <th>Nombre</th>
                                      <th>Apellido</th>
                                      <th>Cedula</th>
                                      <th>Correo</th>
                                      <th>Telefono</th>
                                      <th>Tipo</th>
                                      <th>Tramite</th>
                                      <th>Archivo</th>
                                      
                                      <th>Opción</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                   
                                 
                                                <tr>
                                                 <td>Futbol</td>
                                                  <td>Masculino</td>
                                                  <td>Colombia-Venezuela</td>
                                                  <td>21/11/2017</td>
                                                  <td>4:00 pm</td>
                                                   <td>Cienaga</td>
                                                  
                                                  <td>
                                                    
                                                      <button type='button' class='btn btn-success btn-md' data-toggle="modal" data-target="#editar" id="<?=$pag->getIdPago()?>">
                                                          <i class='fa fa-pencil-square-o fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    <a >
                                                      <button type='button' class='btn btn-danger btn-md'>
                                                          <i class='fa fa-trash fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    </a>
                                                  </td>
                                                </tr>
                                                  <tr>
                                                  <td>Futbol</td>
                                                  <td>Femenino</td>
                                                  <td>Colombia-Peru</td>
                                                  <td>21/11/2017</td>
                                                  <td>4:00 pm</td>
                                                   <td>Santa marta</td>
                                                  
                                                  <td>
                                                    
                                                      <button type='button' class='btn btn-success btn-md' data-toggle="modal" data-target="#editar" id="<?=$pag->getIdPago()?>">
                                                          <i class='fa fa-pencil-square-o fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    <a >
                                                      <button type='button' class='btn btn-danger btn-md'>
                                                          <i class='fa fa-trash fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    </a>
                                                  </td>
                                                </tr>
                                                  <tr>
                                                <td>Ciclismo</td>
                                                  <td>BMX</td>
                                                  <td>Grupo</td>
                                                  <td>21/11/2017</td>
                                                  <td>4:00 pm</td>
                                                   <td>Santa marta</td>
                                                  
                                                  <td>
                                                    
                                                      <button type='button' class='btn btn-success btn-md' data-toggle="modal" data-target="#editar" id="<?=$pag->getIdPago()?>">
                                                          <i class='fa fa-pencil-square-o fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    <a >
                                                      <button type='button' class='btn btn-danger btn-md'>
                                                          <i class='fa fa-trash fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    </a>
                                                  </td>
                                                </tr>
                                                  <tr>
                                                  <td>Futbol</td>
                                                  <td>Masculino</td>
                                                  <td>Colombia-Venezuela</td>
                                                  <td>21/11/2017</td>
                                                  <td>4:00 pm</td>
                                                   <td>Cienaga</td>
                                                  
                                                  <td>
                                                    
                                                      <button type='button' class='btn btn-success btn-md' data-toggle="modal" data-target="#editar" id="<?=$pag->getIdPago()?>">
                                                          <i class='fa fa-pencil-square-o fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    <a >
                                                      <button type='button' class='btn btn-danger btn-md'>
                                                          <i class='fa fa-trash fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    </a>
                                                  </td>
                                                </tr>
                                                  <tr>
                                                  <td>Futbol</td>
                                                  <td>Masculino</td>
                                                  <td>Colombia-Venezuela</td>
                                                  <td>21/11/2017</td>
                                                  <td>4:00 pm</td>
                                                   <td>Cienaga</td>
                                                  
                                                  <td>
                                                    
                                                      <button type='button' class='btn btn-success btn-md' data-toggle="modal" data-target="#editar" id="<?=$pag->getIdPago()?>">
                                                          <i class='fa fa-pencil-square-o fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    <a >
                                                      <button type='button' class='btn btn-danger btn-md'>
                                                          <i class='fa fa-trash fa-1x' aria-hidden='true'></i>
                                                      </button>
                                                    </a>
                                                  </td>
                                                </tr>
                                    
                                                        <tr>
                                                         <td>Futbol</td>
                                                  <td>Masculino</td>
                                                  <td>Colombia-Venezuela</td>
                                                  <td>21/11/2017</td>
                                                  <td>4:00 pm</td>
                                                   <td>Cienaga</td>
                                                          <td>
                                                              
                                                              <button type='button' class='btn btn-success btn-md' data-toggle="modal" data-target="#editar" id="<?=$pag->getIdPago()?>">
                                                                  <i class='fa fa-pencil-square-o fa-1x' aria-hidden='true'></i>
                                                              </button>
                                                              
                                                            <a href="../../control/accion/act_eliminarPago_P.php?Id=<?php echo $pag->getIdPago() ?>">
                                                              <button type='button' class='btn btn-danger btn-md'>
                                                                  <i class='fa fa-trash fa-1x' aria-hidden='true'></i>
                                                              </button>
                                                            </a>
                                                          </td>
                                                        </tr>
                                
                                  </tbody>
                                </table>
                           </div>
                         </div>  
                         
                           
                </div>
                
                
                
                
                
                
                
                
                
                
                
                
                
            </div>
          

        </div>
    

    </div>
   

         
          
           </div>
       </div>
       
      
    </body>
    
</html>